### ISSUE TITLE
Download option not working. 

### ISSUE THREAD

**Issue by NichirinSword** [Killerpac/Kayuri#27]
when i click on download button, app crashes everytime. Could you please fix this issue? 
And one more thing that dark mod is too much dull to see. white letters not bright enough otherwise it’s a great app.

**Comment by Killerpac** [comment]
True, The Ui Needs Some Work To be Done especially the dark mode but currently i am working to reduce the error rate of the app due to gogoanime server changes 

The download Works fine and I cannot reproduce the error.Try Giving Storage Permission From Settings For the App 
If it Doesn't Work Provide the Android Version You are using

**Comment by NichirinSword** [comment]
> True, The Ui Needs Some Work To be Done especially the dark mode but currently i am working to reduce the error rate of the app due to gogoanime server changes
> 
> The download Works fine and I cannot reproduce the error.Try Giving Storage Permission From Settings For the App If it Doesn't Work Provide the Android Version You are using

Not working. After selecting the download quality app just crashing.
Storage permission are already given. I am using Android 9, One UI 1.1

**Comment by Killerpac** [comment]
Ok Will Look into it probably some android 9 related bug because i ahve tested on a oneui 2 and 3 device and it worked
